server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbadminapp?createDatabaseIfNotExist=true
    username: user
    password: user
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: spring-admin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


info:
  application:
    name: admin-app
    version: '@project.version@'